version: "3.8"
services:
  app:
    container_name: francanete-app
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    volumes:
      - .:/app
      - /app/node_modules
      - .next_volume:/app/.next
    command: npm run dev
